import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Montserrat } from "next/font/google";

const poppinsFont = Poppins({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsFont.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
